# -*- coding: utf-8 -*-
"""shipathonn divergent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUzOX7BUWzA8Ush7mKjGRfln7K84K3KR
"""

with open("iitd cse 29.30.txt", 'r') as f:
  txt = f.readlines()
  txt2=[]
  for line in txt:
    if '<Media omitted>\n' not in line:
      a=line[18:-1]
      txt2.append(a)




  d={}
  for line in txt2:
      a=line.split(':')[0]
      if a not in d:
          d[a] = line.split(':')[1:]
      else:
          d[a] += line.split(':')[1:]

  d2={}
  for key in d:
    if d[key]!=[]:
      d2[key]=d[key]






d4={}
for key in d2:
  s=''
  for i in d2[key]:
    s=s+' '+i
    d4[key]=s



from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
d5={}
for key in d4:
    sentence = d4[key]
    embeddings = model.encode(sentence)
    d5[key]=embeddings

with open("Script.txt", 'r') as f:
  script = f.readlines()
  script1=[]
  for i in script:
    if i[0]!="[":
      script1.append(i[:-1])
  script2=[]
  for i in script1:
    if i != '':
      script2.append(i)

  sd={}
  for line in script2:
      b=line.split(':')[0]
      if b not in sd:
          sd[b] = line.split(':')[1:]
      else:
          sd[b] += line.split(':')[1:]


sd4={}
for key in sd:
  s=''
  for i in sd[key]:
    s=s+' '+i
    sd4[key]=s
sd4['Chatur']="study study tension books education boring"
sd4['Director']="competition pressure degree study no fun"
sd4['Pia']='smile pretty happy lively'

from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
sd5={}
for key in sd4:
    sentence = sd4[key]
    embeddings = model.encode(sentence)
    sd5[key]=embeddings



from sentence_transformers import util
d6={}
for key in d5:
  l={}
  for key_sd in sd5:
    similarity=util.cos_sim(d5[key], sd5[key_sd])
    similarity=str(similarity)
    a=similarity[9:-3]
    i=float(a)
    l[key_sd]=i
  d6[key]=l

d7={}
for key in d6:
  max_key=max(d6[key], key=d6[key].get)
  d7[key]=max_key

for key in d7:
  print(key+" : "+d7[key])